# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
variables:
- group: aca variable group

pool:
  vmImage: ubuntu-latest

steps:
  - task: AzureContainerApps@1
    inputs:
      appSourcePath: '$(Build.SourcesDirectory)/src'
      azureSubscription: '$(azureSubscription)'
      # acrName: '$(acrName)'
      resourceGroup: '$(resourceGroup)'
      location: '$(location)'
      # acrUsername: '$(acrUsername)'
      # acrPassword: '$(acrPassword)'
  - task: UseDotNet@2
    displayName: 'Use dotnet 3.1'
    inputs:
      version: 3.1.x
  - task: UseDotNet@2
    displayName: 'Use dotnet 6.0'
    inputs:
      version: 6.0.x
  - task: MicrosoftSecurityDevOps@1
    displayName: 'Microsoft Security DevOps'
